export const SETINICIALSLEAGUE = 'SETINICIALSLEAGUE';
export const SETNAMELEAGUE = 'SETNAMELEAGUE';
export const SETDESCRIPTIONLEAGUE = 'SETDESCRIPTIONLEAGUE';
export const SETOBJECTIVELEAGUE = 'SETOBJECTIVELEAGUE';
export const SETORIENTEDLEAGUE = 'SETORIENTEDLEAGUE';
export const REGISTERLEAGUEDB = 'REGISTERLEAGUEDB';
