export const SETNAMEEVENT = 'SETNAMEEVENT';
export const SETNAMEMANDATE = 'SETNAMEMANDATE';
export const SETDESCRIPTIONMANDATE = 'SETDESCRIPTIONMANDATE';
export const REGISTERMANDATEDB = 'REGISTERMANDATEDB';
